### ISSUE TITLE
Request has been blocked by CORS policy(

### ISSUE THREAD

**Issue by stepGT** [SoLoHK525/valorant-api#6]
Hello! I have CORS...
Do you can help me?)
Thx)
![Screenshot_119](https://user-images.githubusercontent.com/10136237/105073234-84a57500-5ad2-11eb-812f-ced52a7ca564.png)
![Screenshot_120](https://user-images.githubusercontent.com/10136237/105073238-866f3880-5ad2-11eb-9c1b-083e294da78c.png)

**Comment by SoLoHK525** [comment]
Although this is not related to the wrapper, I'll try to provide some advice for you.

The request is being blocked by the browser as the `Access-Control-Allow-Origin` header is not being set by the webserver.

A better solution is to perform requests from your web server rather than on the client-side, in which the front-end sends a request to the server and the server sends a request to RIOT API and returns the result. 

Side note: and it is not recommended to use this API wrapper in the front-end application as it exposes your RIOT API Key.

If you are using express as your webserver right now, you may try to follow [this article](https://medium.com/zero-equals-false/using-cors-in-express-cac7e29b005b) and add Riot's API endpoint to your Access-Control-Allow-Origin header.


Hopefully it helps.

**Comment by stepGT** [comment]
Thanks for the quick response)
I will try
